### ISSUE TITLE
Refine sharing

### ISSUE THREAD

**Issue by webratte** [DavidSM100/CryptoText#1]
Currently if you click "share", Delta Chat opens the contact list.
It would be nice if it would open the chat list.

**Comment by davidsm10** [comment]
> Currently if you click "share", Delta Chat opens the contact list. It would be nice if it would open the chat list.

Hello, I'm sorry for the late answer, I haven't set up notifications yet😅,  answering your question: I don't know why it opens the contact list for you, I have DeltaLab 1.40.0 and Delta chat 1.38.2, in both open the chat list to me (unless I share nothing, meaning leave the textarea in blank, that way open the contact list) but besides that it works perfect. I will update to latest version of DC to see if that's the problem.

**Comment by davidsm10** [comment]
> Currently if you click "share", Delta Chat opens the contact list. It would be nice if it would open the chat list.

Hello, I'm sorry for the late answer, I haven't set up notifications yet😅,  answering your question: I don't know why it opens the contact list for you, I have DeltaLab 1.40.0 and Delta chat 1.38.2, in both open the chat list to me (unless I share nothing, meaning leave the textarea in blank, that way open the chat list) but besides that it works perfect. I will update to latest version of DC to see if that's the problem.

**Comment by webratte** [comment]
Sorry, my fault 🤦🏻‍♂️

I tried to share a empty field 😫

So you can close this issue.

**Comment by davidsm10** [comment]
Don't worry. I will close the issue then.
